version: "3.1"
services:
  back_topmax-app:
    build:
      context: ./back_dashboard
      dockerfile: Dockerfile
    container_name: back_dashboard_app_container
    # image: a7medabdo6/care_managment
    volumes:
      - ./back_dashboard/src:/back_dashboard_App/src:ro
    ports:
      - "7010:7010"
  react:
    build:
      context: ./front_dashboard
      dockerfile: Dockerfile
    container_name: front_dashboard_topmax_container
    volumes:
      - ./front_dashboard/src:/front_dashboard_topmax/src:ro
    ports:
      - "4010:4010"
    environment:
      - NODE_ENV=production
    restart: always

  # nginx:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile.nginx
  #   # volumes:
  #   #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
  #   ports:
  #     - 82:80
  #   restart: always
